name: ci

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          dotnet build BepInEx.ResourceUnloadOptimizations -c Release
      - uses: actions/upload-artifact@v2
        with:
          name: BepInEx.Utility.AllInOne
          path: BepInEx.ResourceUnloadOptimizations/bin/**/*.dll
          if-no-files-found: error
